<a href="https://colab.research.google.com/github/dasdasqs2/Machine-learning/blob/main/wk6_0408.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

tf.random.set_seed(42)

## Diabetes data

In [11]:
xy = np.loadtxt('diabetes_data.csv', delimiter=',', dtype=np.float32)
x_train = xy[:, 0:-1]
y_train = xy[:,[-1]]

print(x_train.shape, y_train.shape)
print(xy)

(759, 8) (759, 1)
[[-0.294118   0.487437   0.180328  ... -0.53117   -0.0333333  0.       ]
 [-0.882353  -0.145729   0.0819672 ... -0.766866  -0.666667   1.       ]
 [-0.0588235  0.839196   0.0491803 ... -0.492741  -0.633333   0.       ]
 ...
 [-0.411765   0.21608    0.180328  ... -0.857387  -0.7        1.       ]
 [-0.882353   0.266332  -0.0163934 ... -0.768574  -0.133333   0.       ]
 [-0.882353  -0.0653266  0.147541  ... -0.797609  -0.933333   1.       ]]


In [13]:
dataset = tf.data.Dataset.from_tensor_slices((x_train,y_train)).batch(len(x_train))

In [14]:
def logistic_regression(features): # features : x_train
  # hypothesis = tf.divide(1., 1. + tf.exp(-tf.matmul(features, W) -b)) # 또는 tf.sigmoid(z)
  z = tf.matmul(features, W) + b
  hypothesis = tf.sigmoid(z)
  return hypothesis

In [15]:
def cost_fn(hypothesis, feature, y):
  cost = -tf.reduce_mean(y * tf.math.log(hypothesis) + (1-y) * tf.math.log(1-hypothesis))
  return cost

In [21]:
def loss_fn(hypothesis, features, labels):
  cost = -tf.reduce_mean(labels + tf.math.log(logistic_regression(features)) + (1-labels) * tf.math.log(1-hypothesis))
  return cost

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

In [31]:
# training 1

EPOCHS = 1001
learning_rate = 0.01

tf.random.set_seed(42)

W = tf.Variable(tf.random.normal((8,1)), name='weight')
b = tf.Variable(tf.random.normal((1,)), name='bias')

for step in range(EPOCHS):
  for features, labels in iter(dataset):
    with tf.GradientTape() as tape:
      loss_value = cost_fn(logistic_regression(features), features, labels)

    W_grad, b_grad = tape.gradient(loss_value, [W,b])
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    

    if step % 100 == 0:
      print("W: {}, b: {}, Iter: {}, Loss: {:.4f}".format(W.numpy(), b.numpy(), step, cost_fn(logistic_regression(features),features,labels)))

W: [[ 0.32733613]
 [-0.84319   ]
 [ 0.31924596]
 [-1.4073014 ]
 [-2.387564  ]
 [-1.0394094 ]
 [-0.55714643]
 [ 0.53974706]], b: [0.08372047], Iter: 0, Loss: 0.6177
W: [[ 0.31157023]
 [-0.89734304]
 [ 0.30192   ]
 [-1.383927  ]
 [-2.339674  ]
 [-1.0554715 ]
 [-0.544102  ]
 [ 0.54020196]], b: [0.04034932], Iter: 100, Loss: 0.6090
W: [[ 0.29191995]
 [-0.94770527]
 [ 0.28696457]
 [-1.3632902 ]
 [-2.2947025 ]
 [-1.0713274 ]
 [-0.53839856]
 [ 0.5351009 ]], b: [0.00824966], Iter: 200, Loss: 0.6021
W: [[ 0.26972958]
 [-0.9951118 ]
 [ 0.27378613]
 [-1.3446898 ]
 [-2.2520504 ]
 [-1.0869464 ]
 [-0.53783727]
 [ 0.52620924]], b: [-0.01577414], Iter: 300, Loss: 0.5961
W: [[ 0.24597195]
 [-1.0401696 ]
 [ 0.26195148]
 [-1.3276025 ]
 [-2.2112594 ]
 [-1.1023059 ]
 [-0.54082316]
 [ 0.51480454]], b: [-0.03404423], Iter: 400, Loss: 0.5907
W: [[ 0.22133607]
 [-1.083316  ]
 [ 0.25114992]
 [-1.3116469 ]
 [-2.1719856 ]
 [-1.1173913 ]
 [-0.54621977]
 [ 0.501795  ]], b: [-0.04821821], Iter: 500, Loss: 0.5857
W: 

In [30]:
# training 2

EPOCHS = 1001

tf.random.set_seed(42)

W = tf.Variable(tf.random.normal((8,1)), name='weight')
b = tf.Variable(tf.random.normal((1,)), name='bias')

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

for step in range(EPOCHS):
  for features, labels in iter(dataset):
    with tf.GradientTape() as tape:
      loss_value = cost_fn(logistic_regression(features), features, labels)

    grads = tape.gradient(loss_value, [W,b])
    optimizer.apply_gradients(grads_and_vars=zip(grads,[W,b]))

    if step % 100 == 0:
      print("W: {}, b: {}, Iter: {}, Loss: {:.4f}".format(W.numpy(), b.numpy(), step, cost_fn(logistic_regression(features),features,labels)))

W: [[ 0.32733613]
 [-0.84319   ]
 [ 0.31924596]
 [-1.4073014 ]
 [-2.387564  ]
 [-1.0394094 ]
 [-0.55714643]
 [ 0.53974706]], b: [0.08372047], Iter: 0, Loss: 0.6177
W: [[ 0.31157023]
 [-0.89734304]
 [ 0.30192   ]
 [-1.383927  ]
 [-2.339674  ]
 [-1.0554715 ]
 [-0.544102  ]
 [ 0.54020196]], b: [0.04034932], Iter: 100, Loss: 0.6090
W: [[ 0.29191995]
 [-0.94770527]
 [ 0.28696457]
 [-1.3632902 ]
 [-2.2947025 ]
 [-1.0713274 ]
 [-0.53839856]
 [ 0.5351009 ]], b: [0.00824967], Iter: 200, Loss: 0.6021
W: [[ 0.26972958]
 [-0.9951118 ]
 [ 0.27378613]
 [-1.3446898 ]
 [-2.2520504 ]
 [-1.0869464 ]
 [-0.53783727]
 [ 0.5262093 ]], b: [-0.01577413], Iter: 300, Loss: 0.5961
W: [[ 0.24597195]
 [-1.0401696 ]
 [ 0.2619515 ]
 [-1.3276025 ]
 [-2.2112594 ]
 [-1.1023059 ]
 [-0.54082316]
 [ 0.5148046 ]], b: [-0.03404422], Iter: 400, Loss: 0.5907
W: [[ 0.22133607]
 [-1.083316  ]
 [ 0.25114995]
 [-1.3116469 ]
 [-2.1719856 ]
 [-1.1173913 ]
 [-0.54621977]
 [ 0.50179505]], b: [-0.04821819], Iter: 500, Loss: 0.5857
W: 

## Toy data

In [39]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]

#one-hot encoding style
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

#convert into numpy and float format
x_data = np.asarray(x_data, dtype = np.float32)
y_data = np.asarray(y_data, dtype = np.float32)

In [40]:
nb_classes = 3

print(x_data.shape)
print(y_data.shape)

(8, 4)
(8, 3)


In [63]:
tf.random.set_seed(42)

W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
variables = [W, b]

print(W.numpy(), b.numpy())

[[ 0.3274685  -0.8426258   0.3194337 ]
 [-1.4075519  -2.3880599  -1.0392479 ]
 [-0.5573232   0.539707    1.6994323 ]
 [ 0.28893656 -1.5066116  -0.26454744]] [ 0.08422458 -0.86090374  0.37812304]


In [64]:
# softmax
def hypothesis(X):
  return tf.nn.softmax(tf.matmul(X, W) + b)

print(hypothesis(x_data))

tf.Tensor(
[[6.14394099e-02 5.18557208e-04 9.38042045e-01]
 [1.81572989e-03 1.88858321e-05 9.98165429e-01]
 [5.51678007e-03 4.90921536e-07 9.94482756e-01]
 [1.06589345e-04 4.38476322e-09 9.99893427e-01]
 [1.14175309e-05 4.37850659e-11 9.99988556e-01]
 [1.25215898e-04 1.07340261e-08 9.99874711e-01]
 [3.00473948e-06 1.52766064e-11 9.99997020e-01]
 [3.78559264e-07 3.59057185e-13 9.99999642e-01]], shape=(8, 3), dtype=float32)


In [43]:
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

print(hypothesis(sample_db))

tf.Tensor([[2.6716635e-01 2.8614273e-09 7.3283368e-01]], shape=(1, 3), dtype=float32)


In [65]:
def cost_fn(X, Y):
  logits = hypothesis(X)
  cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1)
  cost_mean = tf.reduce_mean(cost)

  return cost_mean

In [66]:
def grad_fn(X,Y):
  with tf.GradientTape() as tape:
    loss = cost_fn(X, Y)
    grads = tape.gradient(loss, variables)

    return grads

print(grad_fn(x_data, y_data))

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.23972654, -0.74993026,  0.9896568 ],
       [-1.6086664 , -1.2498679 ,  2.8585343 ],
       [-1.6144158 , -1.8749278 ,  3.4893436 ],
       [-1.6139375 , -1.9999301 ,  3.6138678 ]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.24137267, -0.37493277,  0.6163054 ], dtype=float32)>]


In [73]:
def fit(X,Y,epochs=200, verbose=100):
  optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)

  for i in range(epochs):
    grads = grad_fn(X,Y)
    optimizer.apply_gradients(zip(grads, variables))
    if (i==0) | ((i+1)%verbose==0):
      print('Loss at epoch %d: %f' %(i+1, cost_fn(X,Y).numpy()))

fit(x_data, y_data)

Loss at epoch 1: 5.996902
Loss at epoch 100: 0.755535
Loss at epoch 200: 0.683668


### Prediction

In [74]:
sample_data = [[2,1,3,2]]
sample_data = np.asarray(sample_data, dtype = np.float32)

a = hypothesis(sample_data)

print(a)
print(tf.argmax(a,1))

tf.Tensor([[0.01092461 0.16124442 0.827831  ]], shape=(1, 3), dtype=float32)
tf.Tensor([2], shape=(1,), dtype=int64)


In [75]:
b = hypothesis(x_data)
print(b)
print(tf.argmax(b,1))
print(tf.argmax(y_data, 1))

tf.Tensor(
[[0.040218   0.04007221 0.9197098 ]
 [0.01092461 0.1612444  0.827831  ]
 [0.01666104 0.25118652 0.73215246]
 [0.00401505 0.46371803 0.53226686]
 [0.92029846 0.04604038 0.03366122]
 [0.5748588  0.41796598 0.0071752 ]
 [0.8981068  0.09377893 0.00811421]
 [0.9432748  0.05498048 0.00174477]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 2 0 0 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


In [79]:
class softmax_classifer(tf.keras.Model):
  def __init__(self,nb_classes):
    super(softmax_classifer, self).__init__()
    self.W = tf.Variable(tf.random.normal((4, nb_classes)), name = 'weight')
    self.b = tf.Variable(tf.random.normal((nb_classes,)), name = 'bias')

  def softmax_regression(self,X):
    return tf.nn.softmax(tf.matmul(X,self.W) + self.b)

  def cost_fn(self, X, Y):
    logits = self.softmax_regression(X)
    cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(logits), axis=1))
    return cost
  
  def grad_fn(self, X, Y):
    with tf.GradientTape() as tape:
      cost = self.cost_fn(x_data, y_data)
      grads = tape.gradient(cost, self.variables)
      return grads

  def fit(self, X, Y, epochs=200, verbose=500):
    optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)

    for i in range(epochs):
      grads = self.grad_fn(X, Y)
      optimizer.apply_gradients(zip(grads, self.variables))
      if (i==0) | ((i+1)%verbose==0):
        print('Loss at epoch %d: %f' %(i+1, self.cost_fn(X,Y).numpy()))

model = softmax_classifer(nb_classes)
model.fit(x_data, y_data)

Loss at epoch 1: 4.601841
